/** Справочник специалистов для сида (иконки — ключи из lib/specialist-icons) */
export const SEED_SPECIALISTS: { name: string; iconKey: string }[] = [
  { name: "Аллерголог", iconKey: "wind" },
  { name: "Гастроэнтеролог", iconKey: "apple" },
  { name: "Гинеколог", iconKey: "venus" },
  { name: "Диетолог", iconKey: "salad" },
  { name: "Оториноларинголог", iconKey: "ear" },
  { name: "Кардиолог", iconKey: "heart_pulse" },
  { name: "Косметолог", iconKey: "sparkles" },
  { name: "Дерматолог", iconKey: "droplet" },
  { name: "ЛФК", iconKey: "dumbbell" },
  { name: "Невролог", iconKey: "brain" },
  { name: "Неонатолог", iconKey: "baby" },
  { name: "Нефролог", iconKey: "droplets" },
  { name: "Ортодонт", iconKey: "smile" },
  { name: "Ортопед", iconKey: "bone" },
  { name: "Офтальмолог", iconKey: "eye" },
  { name: "Педиатр", iconKey: "users" },
  { name: "Психиатр", iconKey: "brain_circuit" },
  { name: "Психолог", iconKey: "message_circle" },
  { name: "Пульмонолог", iconKey: "pill" },
  { name: "Ревматолог", iconKey: "activity" },
  { name: "Стоматолог", iconKey: "smile_plus" },
  { name: "Сурдолог", iconKey: "mic" },
  { name: "Уролог", iconKey: "droplet" },
  { name: "Физиотерапевт", iconKey: "zap" },
  { name: "Фтизиатр", iconKey: "stethoscope" },
  { name: "Функциональная диагностика", iconKey: "line_chart" },
  { name: "МРТ", iconKey: "scan" },
  { name: "КТ", iconKey: "box" },
  { name: "УЗИ", iconKey: "radio" },
  { name: "Хирург", iconKey: "scissors" },
  { name: "Эндокринолог", iconKey: "flask_conical" },
];
